title: La science informatique
author: romuald.thion@unc.nc
subtitle: _pourquoi je ne vais ni réparer ton  imprimante ni hacker ton Insta_
date: 29 juillet 2022
keywords: [informatique, UNC]
abstract: |
  Exposé proposé pour l'action _"Les lycéens à la fac"_ du salon des études supérieures du 29 juillet 2022 de l'UNC (13h, Amphi A400).

# revealjs-url: "/home/romulus/Install/reveal.js"
progress: true
slideNumber: true
width: 960
height: 700
margin: 0.02
minScale: 0.5
maxScale: 1.0
